/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const ResourceId = IDL.Nat;
export const UserId = IDL.Principal;
export const Announcement = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishAt' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'expireAt' : IDL.Opt(Timestamp),
  'isPinned' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlogPost = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : Timestamp,
  'featuredImageBlob' : IDL.Opt(ExternalBlob),
  'author' : UserId,
  'updatedAt' : Timestamp,
});
export const Devotional = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'scripture' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'reflection' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : ResourceId,
  'blob' : ExternalBlob,
  'caption' : IDL.Opt(IDL.Text),
  'albumId' : ResourceId,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
});
export const LeadershipMember = IDL.Record({
  'id' : ResourceId,
  'bio' : IDL.Text,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Sermon = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'videoBlob' : IDL.Opt(ExternalBlob),
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'scriptureReference' : IDL.Text,
  'speaker' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
  'leader' : IDL.Null,
  'guest' : IDL.Null,
});
export const GalleryAlbum = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'coverImageBlob' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'endDate' : Timestamp,
  'isPublished' : IDL.Bool,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'capacity' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
  'startDate' : Timestamp,
});
export const AnalyticsSummary = IDL.Record({
  'totalEvents' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalPageViews' : IDL.Nat,
  'totalDonations' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'totalDonationAmountCents' : IDL.Nat,
});
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'role' : UserRole,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'registrationStatus' : RegistrationStatus,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const RsvpStatus = IDL.Variant({
  'maybe' : IDL.Null,
  'notGoing' : IDL.Null,
  'going' : IDL.Null,
});
export const Rsvp = IDL.Record({
  'status' : RsvpStatus,
  'userId' : UserId,
  'registeredAt' : Timestamp,
});
export const EventWithRsvps = IDL.Record({
  'event' : Event,
  'rsvps' : IDL.Vec(Rsvp),
});
export const SocialLinks = IDL.Record({
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'whatsapp' : IDL.Opt(IDL.Text),
  'facebook' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
});
export const SystemSettings = IDL.Record({
  'aboutUs' : IDL.Text,
  'primaryColor' : IDL.Text,
  'socialLinks' : SocialLinks,
  'churchName' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'contactEmail' : IDL.Text,
  'welcomeMessage' : IDL.Text,
  'contactPhone' : IDL.Opt(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'id' : ResourceId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Donation = IDL.Record({
  'id' : ResourceId,
  'donorId' : IDL.Opt(UserId),
  'createdAt' : Timestamp,
  'donorName' : IDL.Text,
  'amountCents' : IDL.Nat,
  'message' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'donorEmail' : IDL.Text,
});
export const MediaType = IDL.Variant({
  'pdf' : IDL.Null,
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const MediaFile = IDL.Record({
  'id' : ResourceId,
  'blob' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
  'fileName' : IDL.Text,
  'mediaType' : MediaType,
  'category' : IDL.Text,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
});
export const PrayerStatus = IDL.Variant({
  'active' : IDL.Null,
  'answered' : IDL.Null,
});
export const PrayerPrivacy = IDL.Variant({
  'public' : IDL.Null,
  'private' : IDL.Null,
  'membersOnly' : IDL.Null,
});
export const PrayerRequest = IDL.Record({
  'id' : ResourceId,
  'status' : PrayerStatus,
  'submitterName' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'submitterId' : IDL.Opt(UserId),
  'privacy' : PrayerPrivacy,
});
export const NewsletterSubscriber = IDL.Record({
  'subscribedAt' : Timestamp,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : ResourceId,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'isApproved' : IDL.Bool,
  'content' : IDL.Text,
  'authorId' : IDL.Opt(UserId),
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'isFeatured' : IDL.Bool,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, Timestamp, IDL.Opt(Timestamp)],
      [Announcement],
      [],
    ),
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [BlogPost],
      [],
    ),
  'addDevotional' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Timestamp],
      [Devotional],
      [],
    ),
  'addGalleryImage' : IDL.Func(
      [ResourceId, ExternalBlob, IDL.Opt(IDL.Text)],
      [GalleryImage],
      [],
    ),
  'addLeader' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat],
      [LeadershipMember],
      [],
    ),
  'addSermon' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Timestamp,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [Sermon],
      [],
    ),
  'approveTestimonial' : IDL.Func([ResourceId, IDL.Bool], [], []),
  'approveUser' : IDL.Func([UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignUserRole' : IDL.Func([UserId, UserRole], [], []),
  'createAlbum' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(ExternalBlob)],
      [GalleryAlbum],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDonationCheckout' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Timestamp,
        Timestamp,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [Event],
      [],
    ),
  'deleteAlbum' : IDL.Func([ResourceId], [], []),
  'deleteAnnouncement' : IDL.Func([ResourceId], [], []),
  'deleteBlogPost' : IDL.Func([ResourceId], [], []),
  'deleteDevotional' : IDL.Func([ResourceId], [], []),
  'deleteEvent' : IDL.Func([ResourceId], [], []),
  'deleteGalleryImage' : IDL.Func([ResourceId], [], []),
  'deleteLeader' : IDL.Func([ResourceId], [], []),
  'deleteMedia' : IDL.Func([ResourceId], [], []),
  'deleteSermon' : IDL.Func([ResourceId], [], []),
  'deleteTestimonial' : IDL.Func([ResourceId], [], []),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDonationSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getEvent' : IDL.Func([ResourceId], [IDL.Opt(Event)], ['query']),
  'getEventWithRsvps' : IDL.Func(
      [ResourceId],
      [IDL.Opt(EventWithRsvps)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [SystemSettings], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlbums' : IDL.Func([], [IDL.Vec(GalleryAlbum)], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listDevotionals' : IDL.Func([], [IDL.Vec(Devotional)], ['query']),
  'listDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listGalleryImages' : IDL.Func(
      [ResourceId],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'listLeadership' : IDL.Func([], [IDL.Vec(LeadershipMember)], ['query']),
  'listMedia' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
  'listMediaByType' : IDL.Func([MediaType], [IDL.Vec(MediaFile)], ['query']),
  'listPendingRegistrations' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
  'listSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
  'listSubscribers' : IDL.Func([], [IDL.Vec(NewsletterSubscriber)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markContactRead' : IDL.Func([ResourceId], [], []),
  'recordDonation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Donation],
      [],
    ),
  'recordPageView' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [UserProfile],
      [],
    ),
  'rejectUser' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessage],
      [],
    ),
  'submitPrayerRequest' : IDL.Func(
      [IDL.Text, IDL.Text, PrayerPrivacy],
      [PrayerRequest],
      [],
    ),
  'submitRsvp' : IDL.Func([ResourceId, RsvpStatus], [], []),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [Testimonial],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'totalDonationsCents' : IDL.Func([], [IDL.Nat], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unsubscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateAnnouncement' : IDL.Func(
      [ResourceId, IDL.Text, IDL.Text, IDL.Bool, Timestamp, IDL.Opt(Timestamp)],
      [Announcement],
      [],
    ),
  'updateBlogPost' : IDL.Func(
      [ResourceId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [BlogPost],
      [],
    ),
  'updateDevotional' : IDL.Func(
      [ResourceId, IDL.Text, IDL.Text, IDL.Text, Timestamp],
      [Devotional],
      [],
    ),
  'updateEvent' : IDL.Func(
      [
        ResourceId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Timestamp,
        Timestamp,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [Event],
      [],
    ),
  'updateLeader' : IDL.Func(
      [
        ResourceId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Nat,
        IDL.Bool,
      ],
      [LeadershipMember],
      [],
    ),
  'updatePrayerStatus' : IDL.Func([ResourceId, PrayerStatus], [], []),
  'updateSermon' : IDL.Func(
      [
        ResourceId,
        IDL.Text,
        IDL.Text,
        Timestamp,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Bool,
      ],
      [Sermon],
      [],
    ),
  'updateSettings' : IDL.Func([SystemSettings], [], []),
  'uploadMedia' : IDL.Func(
      [IDL.Text, ExternalBlob, MediaType, IDL.Text, IDL.Opt(IDL.Text)],
      [MediaFile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const ResourceId = IDL.Nat;
  const UserId = IDL.Principal;
  const Announcement = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishAt' : Timestamp,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'expireAt' : IDL.Opt(Timestamp),
    'isPinned' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlogPost = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : Timestamp,
    'featuredImageBlob' : IDL.Opt(ExternalBlob),
    'author' : UserId,
    'updatedAt' : Timestamp,
  });
  const Devotional = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'scripture' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'reflection' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : ResourceId,
    'blob' : ExternalBlob,
    'caption' : IDL.Opt(IDL.Text),
    'albumId' : ResourceId,
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
  });
  const LeadershipMember = IDL.Record({
    'id' : ResourceId,
    'bio' : IDL.Text,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Sermon = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'videoBlob' : IDL.Opt(ExternalBlob),
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'scriptureReference' : IDL.Text,
    'speaker' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'leader' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GalleryAlbum = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'coverImageBlob' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'endDate' : Timestamp,
    'isPublished' : IDL.Bool,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'capacity' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
    'startDate' : Timestamp,
  });
  const AnalyticsSummary = IDL.Record({
    'totalEvents' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalPageViews' : IDL.Nat,
    'totalDonations' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'totalDonationAmountCents' : IDL.Nat,
  });
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'role' : UserRole,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'registrationStatus' : RegistrationStatus,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const RsvpStatus = IDL.Variant({
    'maybe' : IDL.Null,
    'notGoing' : IDL.Null,
    'going' : IDL.Null,
  });
  const Rsvp = IDL.Record({
    'status' : RsvpStatus,
    'userId' : UserId,
    'registeredAt' : Timestamp,
  });
  const EventWithRsvps = IDL.Record({
    'event' : Event,
    'rsvps' : IDL.Vec(Rsvp),
  });
  const SocialLinks = IDL.Record({
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'whatsapp' : IDL.Opt(IDL.Text),
    'facebook' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
  });
  const SystemSettings = IDL.Record({
    'aboutUs' : IDL.Text,
    'primaryColor' : IDL.Text,
    'socialLinks' : SocialLinks,
    'churchName' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'contactEmail' : IDL.Text,
    'welcomeMessage' : IDL.Text,
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'id' : ResourceId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Donation = IDL.Record({
    'id' : ResourceId,
    'donorId' : IDL.Opt(UserId),
    'createdAt' : Timestamp,
    'donorName' : IDL.Text,
    'amountCents' : IDL.Nat,
    'message' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'donorEmail' : IDL.Text,
  });
  const MediaType = IDL.Variant({
    'pdf' : IDL.Null,
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const MediaFile = IDL.Record({
    'id' : ResourceId,
    'blob' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
    'fileName' : IDL.Text,
    'mediaType' : MediaType,
    'category' : IDL.Text,
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
  });
  const PrayerStatus = IDL.Variant({
    'active' : IDL.Null,
    'answered' : IDL.Null,
  });
  const PrayerPrivacy = IDL.Variant({
    'public' : IDL.Null,
    'private' : IDL.Null,
    'membersOnly' : IDL.Null,
  });
  const PrayerRequest = IDL.Record({
    'id' : ResourceId,
    'status' : PrayerStatus,
    'submitterName' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'submitterId' : IDL.Opt(UserId),
    'privacy' : PrayerPrivacy,
  });
  const NewsletterSubscriber = IDL.Record({
    'subscribedAt' : Timestamp,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : ResourceId,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'isApproved' : IDL.Bool,
    'content' : IDL.Text,
    'authorId' : IDL.Opt(UserId),
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'isFeatured' : IDL.Bool,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, Timestamp, IDL.Opt(Timestamp)],
        [Announcement],
        [],
      ),
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [BlogPost],
        [],
      ),
    'addDevotional' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Timestamp],
        [Devotional],
        [],
      ),
    'addGalleryImage' : IDL.Func(
        [ResourceId, ExternalBlob, IDL.Opt(IDL.Text)],
        [GalleryImage],
        [],
      ),
    'addLeader' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat],
        [LeadershipMember],
        [],
      ),
    'addSermon' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Timestamp,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [Sermon],
        [],
      ),
    'approveTestimonial' : IDL.Func([ResourceId, IDL.Bool], [], []),
    'approveUser' : IDL.Func([UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignUserRole' : IDL.Func([UserId, UserRole], [], []),
    'createAlbum' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(ExternalBlob)],
        [GalleryAlbum],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDonationCheckout' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Timestamp,
          Timestamp,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [Event],
        [],
      ),
    'deleteAlbum' : IDL.Func([ResourceId], [], []),
    'deleteAnnouncement' : IDL.Func([ResourceId], [], []),
    'deleteBlogPost' : IDL.Func([ResourceId], [], []),
    'deleteDevotional' : IDL.Func([ResourceId], [], []),
    'deleteEvent' : IDL.Func([ResourceId], [], []),
    'deleteGalleryImage' : IDL.Func([ResourceId], [], []),
    'deleteLeader' : IDL.Func([ResourceId], [], []),
    'deleteMedia' : IDL.Func([ResourceId], [], []),
    'deleteSermon' : IDL.Func([ResourceId], [], []),
    'deleteTestimonial' : IDL.Func([ResourceId], [], []),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDonationSessionStatus' : IDL.Func(
        [IDL.Text],
        [StripeSessionStatus],
        [],
      ),
    'getEvent' : IDL.Func([ResourceId], [IDL.Opt(Event)], ['query']),
    'getEventWithRsvps' : IDL.Func(
        [ResourceId],
        [IDL.Opt(EventWithRsvps)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [SystemSettings], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlbums' : IDL.Func([], [IDL.Vec(GalleryAlbum)], ['query']),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listDevotionals' : IDL.Func([], [IDL.Vec(Devotional)], ['query']),
    'listDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listGalleryImages' : IDL.Func(
        [ResourceId],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'listLeadership' : IDL.Func([], [IDL.Vec(LeadershipMember)], ['query']),
    'listMedia' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
    'listMediaByType' : IDL.Func([MediaType], [IDL.Vec(MediaFile)], ['query']),
    'listPendingRegistrations' : IDL.Func(
        [],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'listPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
    'listSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
    'listSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscriber)],
        ['query'],
      ),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markContactRead' : IDL.Func([ResourceId], [], []),
    'recordDonation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Donation],
        [],
      ),
    'recordPageView' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
    'rejectUser' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
    'submitPrayerRequest' : IDL.Func(
        [IDL.Text, IDL.Text, PrayerPrivacy],
        [PrayerRequest],
        [],
      ),
    'submitRsvp' : IDL.Func([ResourceId, RsvpStatus], [], []),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [Testimonial],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'totalDonationsCents' : IDL.Func([], [IDL.Nat], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unsubscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateAnnouncement' : IDL.Func(
        [
          ResourceId,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          Timestamp,
          IDL.Opt(Timestamp),
        ],
        [Announcement],
        [],
      ),
    'updateBlogPost' : IDL.Func(
        [ResourceId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [BlogPost],
        [],
      ),
    'updateDevotional' : IDL.Func(
        [ResourceId, IDL.Text, IDL.Text, IDL.Text, Timestamp],
        [Devotional],
        [],
      ),
    'updateEvent' : IDL.Func(
        [
          ResourceId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Timestamp,
          Timestamp,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [Event],
        [],
      ),
    'updateLeader' : IDL.Func(
        [
          ResourceId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Nat,
          IDL.Bool,
        ],
        [LeadershipMember],
        [],
      ),
    'updatePrayerStatus' : IDL.Func([ResourceId, PrayerStatus], [], []),
    'updateSermon' : IDL.Func(
        [
          ResourceId,
          IDL.Text,
          IDL.Text,
          Timestamp,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Bool,
        ],
        [Sermon],
        [],
      ),
    'updateSettings' : IDL.Func([SystemSettings], [], []),
    'uploadMedia' : IDL.Func(
        [IDL.Text, ExternalBlob, MediaType, IDL.Text, IDL.Opt(IDL.Text)],
        [MediaFile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };