/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalEvents' : bigint,
  'totalUsers' : bigint,
  'totalPageViews' : bigint,
  'totalDonations' : bigint,
  'totalMembers' : bigint,
  'totalDonationAmountCents' : bigint,
}
export interface Announcement {
  'id' : ResourceId,
  'title' : string,
  'content' : string,
  'publishAt' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'expireAt' : [] | [Timestamp],
  'isPinned' : boolean,
}
export interface BlogPost {
  'id' : ResourceId,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : Timestamp,
  'featuredImageBlob' : [] | [ExternalBlob],
  'author' : UserId,
  'updatedAt' : Timestamp,
}
export interface ContactMessage {
  'id' : ResourceId,
  'subject' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
}
export interface Devotional {
  'id' : ResourceId,
  'title' : string,
  'scripture' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'reflection' : string,
}
export interface Donation {
  'id' : ResourceId,
  'donorId' : [] | [UserId],
  'createdAt' : Timestamp,
  'donorName' : string,
  'amountCents' : bigint,
  'message' : [] | [string],
  'currency' : string,
  'stripeSessionId' : [] | [string],
  'donorEmail' : string,
}
export interface Event {
  'id' : ResourceId,
  'title' : string,
  'endDate' : Timestamp,
  'isPublished' : boolean,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'imageUrl' : [] | [string],
  'capacity' : [] | [bigint],
  'location' : string,
  'startDate' : Timestamp,
}
export interface EventWithRsvps { 'event' : Event, 'rsvps' : Array<Rsvp> }
export type ExternalBlob = Uint8Array;
export interface GalleryAlbum {
  'id' : ResourceId,
  'title' : string,
  'coverImageBlob' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : [] | [string],
  'category' : string,
}
export interface GalleryImage {
  'id' : ResourceId,
  'blob' : ExternalBlob,
  'caption' : [] | [string],
  'albumId' : ResourceId,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
}
export interface LeadershipMember {
  'id' : ResourceId,
  'bio' : string,
  'photoBlob' : [] | [ExternalBlob],
  'title' : string,
  'displayOrder' : bigint,
  'name' : string,
  'isActive' : boolean,
}
export interface MediaFile {
  'id' : ResourceId,
  'blob' : ExternalBlob,
  'description' : [] | [string],
  'fileName' : string,
  'mediaType' : MediaType,
  'category' : string,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
}
export type MediaType = { 'pdf' : null } |
  { 'audio' : null } |
  { 'video' : null } |
  { 'image' : null };
export interface NewsletterSubscriber {
  'subscribedAt' : Timestamp,
  'isActive' : boolean,
  'email' : string,
}
export type PrayerPrivacy = { 'public' : null } |
  { 'private' : null } |
  { 'membersOnly' : null };
export interface PrayerRequest {
  'id' : ResourceId,
  'status' : PrayerStatus,
  'submitterName' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'submitterId' : [] | [UserId],
  'privacy' : PrayerPrivacy,
}
export type PrayerStatus = { 'active' : null } |
  { 'answered' : null };
export type RegistrationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ResourceId = bigint;
export interface Rsvp {
  'status' : RsvpStatus,
  'userId' : UserId,
  'registeredAt' : Timestamp,
}
export type RsvpStatus = { 'maybe' : null } |
  { 'notGoing' : null } |
  { 'going' : null };
export interface Sermon {
  'id' : ResourceId,
  'title' : string,
  'isPublished' : boolean,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'audioBlob' : [] | [ExternalBlob],
  'videoBlob' : [] | [ExternalBlob],
  'thumbnailBlob' : [] | [ExternalBlob],
  'scriptureReference' : string,
  'speaker' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SocialLinks {
  'twitter' : [] | [string],
  'instagram' : [] | [string],
  'whatsapp' : [] | [string],
  'facebook' : [] | [string],
  'youtube' : [] | [string],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SystemSettings {
  'aboutUs' : string,
  'primaryColor' : string,
  'socialLinks' : SocialLinks,
  'churchName' : string,
  'logoUrl' : [] | [string],
  'address' : [] | [string],
  'contactEmail' : string,
  'welcomeMessage' : string,
  'contactPhone' : [] | [string],
}
export interface Testimonial {
  'id' : ResourceId,
  'photoBlob' : [] | [ExternalBlob],
  'isApproved' : boolean,
  'content' : string,
  'authorId' : [] | [UserId],
  'createdAt' : Timestamp,
  'authorName' : string,
  'isFeatured' : boolean,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'joinedAt' : Timestamp,
  'role' : UserRole,
  'photoUrl' : [] | [string],
  'email' : string,
  'phone' : [] | [string],
  'registrationStatus' : RegistrationStatus,
}
export type UserRole = { 'member' : null } |
  { 'admin' : null } |
  { 'leader' : null } |
  { 'guest' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAnnouncement' : ActorMethod<
    [string, string, boolean, Timestamp, [] | [Timestamp]],
    Announcement
  >,
  'addBlogPost' : ActorMethod<
    [string, string, [] | [ExternalBlob], boolean],
    BlogPost
  >,
  'addDevotional' : ActorMethod<
    [string, string, string, Timestamp],
    Devotional
  >,
  'addGalleryImage' : ActorMethod<
    [ResourceId, ExternalBlob, [] | [string]],
    GalleryImage
  >,
  'addLeader' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], bigint],
    LeadershipMember
  >,
  'addSermon' : ActorMethod<
    [
      string,
      string,
      Timestamp,
      string,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    Sermon
  >,
  'approveTestimonial' : ActorMethod<[ResourceId, boolean], undefined>,
  'approveUser' : ActorMethod<[UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignUserRole' : ActorMethod<[UserId, UserRole], undefined>,
  'createAlbum' : ActorMethod<
    [string, [] | [string], string, [] | [ExternalBlob]],
    GalleryAlbum
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDonationCheckout' : ActorMethod<
    [string, string, bigint, string, [] | [string], string, string],
    string
  >,
  'createEvent' : ActorMethod<
    [
      string,
      string,
      string,
      Timestamp,
      Timestamp,
      [] | [bigint],
      [] | [string],
    ],
    Event
  >,
  'deleteAlbum' : ActorMethod<[ResourceId], undefined>,
  'deleteAnnouncement' : ActorMethod<[ResourceId], undefined>,
  'deleteBlogPost' : ActorMethod<[ResourceId], undefined>,
  'deleteDevotional' : ActorMethod<[ResourceId], undefined>,
  'deleteEvent' : ActorMethod<[ResourceId], undefined>,
  'deleteGalleryImage' : ActorMethod<[ResourceId], undefined>,
  'deleteLeader' : ActorMethod<[ResourceId], undefined>,
  'deleteMedia' : ActorMethod<[ResourceId], undefined>,
  'deleteSermon' : ActorMethod<[ResourceId], undefined>,
  'deleteTestimonial' : ActorMethod<[ResourceId], undefined>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDonationSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getEvent' : ActorMethod<[ResourceId], [] | [Event]>,
  'getEventWithRsvps' : ActorMethod<[ResourceId], [] | [EventWithRsvps]>,
  'getSettings' : ActorMethod<[], SystemSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAlbums' : ActorMethod<[], Array<GalleryAlbum>>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listContacts' : ActorMethod<[], Array<ContactMessage>>,
  'listDevotionals' : ActorMethod<[], Array<Devotional>>,
  'listDonations' : ActorMethod<[], Array<Donation>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listGalleryImages' : ActorMethod<[ResourceId], Array<GalleryImage>>,
  'listLeadership' : ActorMethod<[], Array<LeadershipMember>>,
  'listMedia' : ActorMethod<[], Array<MediaFile>>,
  'listMediaByType' : ActorMethod<[MediaType], Array<MediaFile>>,
  'listPendingRegistrations' : ActorMethod<[], Array<UserProfile>>,
  'listPrayerRequests' : ActorMethod<[], Array<PrayerRequest>>,
  'listSermons' : ActorMethod<[], Array<Sermon>>,
  'listSubscribers' : ActorMethod<[], Array<NewsletterSubscriber>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'markContactRead' : ActorMethod<[ResourceId], undefined>,
  'recordDonation' : ActorMethod<
    [string, string, bigint, string, [] | [string], [] | [string]],
    Donation
  >,
  'recordPageView' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[string, string, [] | [string]], UserProfile>,
  'rejectUser' : ActorMethod<[UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    ContactMessage
  >,
  'submitPrayerRequest' : ActorMethod<
    [string, string, PrayerPrivacy],
    PrayerRequest
  >,
  'submitRsvp' : ActorMethod<[ResourceId, RsvpStatus], undefined>,
  'submitTestimonial' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    Testimonial
  >,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'totalDonationsCents' : ActorMethod<[], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unsubscribeNewsletter' : ActorMethod<[string], undefined>,
  'updateAnnouncement' : ActorMethod<
    [ResourceId, string, string, boolean, Timestamp, [] | [Timestamp]],
    Announcement
  >,
  'updateBlogPost' : ActorMethod<
    [ResourceId, string, string, [] | [ExternalBlob], boolean],
    BlogPost
  >,
  'updateDevotional' : ActorMethod<
    [ResourceId, string, string, string, Timestamp],
    Devotional
  >,
  'updateEvent' : ActorMethod<
    [
      ResourceId,
      string,
      string,
      string,
      Timestamp,
      Timestamp,
      [] | [bigint],
      [] | [string],
      boolean,
    ],
    Event
  >,
  'updateLeader' : ActorMethod<
    [ResourceId, string, string, string, [] | [ExternalBlob], bigint, boolean],
    LeadershipMember
  >,
  'updatePrayerStatus' : ActorMethod<[ResourceId, PrayerStatus], undefined>,
  'updateSermon' : ActorMethod<
    [
      ResourceId,
      string,
      string,
      Timestamp,
      string,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      boolean,
    ],
    Sermon
  >,
  'updateSettings' : ActorMethod<[SystemSettings], undefined>,
  'uploadMedia' : ActorMethod<
    [string, ExternalBlob, MediaType, string, [] | [string]],
    MediaFile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];